---
- name: Set up WordPress on EC2
  hosts: wordpress
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Create WordPress docker-compose file
      copy:
        dest: /home/ubuntu/docker-compose.yml
        content: |
          version: '3.1'

          services:
            wordpress:
              image: wordpress
              restart: always
              ports:
                - 80:80
              environment:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: wp_user
                WORDPRESS_DB_PASSWORD: wp_pass
                WORDPRESS_DB_NAME: wordpress
              volumes:
                - wordpress_data:/var/www/html

            db:
              image: mysql:5.7
              restart: always
              environment:
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wp_user
                MYSQL_PASSWORD: wp_pass
                MYSQL_ROOT_PASSWORD: somewordpress
              volumes:
                - db_data:/var/lib/mysql

          volumes:
            wordpress_data:
            db_data:

    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu
